apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod-gpu
  labels:
    app: ubuntu-pod
spec:
  containers:
  - image: nvidia/cuda:11.0.3-base-ubuntu20.04
    name: ubuntu
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
    securityContext:
      privileged: true
    args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 99999; done']
